export { default as logo } from "../assets/images/logo.png";
export { default as search } from "../assets/icons/searchnormal1.png";
export { default as profile } from "../assets/icons/profile.png";
export { default as shoppingcart } from "../assets/icons/shoppingcart.png";
export { default as heroBanner } from "../assets/images/hero.png";
export { default as feature1 } from "../assets/images/Group 4117.png";
export { default as feature2 } from "../assets/images/Group 4118.png";
export { default as feature3 } from "../assets/images/Group 4119.png";
export { default as feature4 } from "../assets/images/Group 4120.png";
export { default as cigar } from "../assets/images/about-cigar.png";
export { default as cigarSmoke } from "../assets/images/cigar-smoke.png";
export { default as play } from "../assets/icons/play.png";
